name: Pakcage and release extension

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install dependencies
        run: |
          npm install -g @vscode/vsce
          npm install
      - name: Package extension
        run: |
          vsce package
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::gitpod-config-generator-0.0.1-$(date +"%Y.%m.%d_%H-%M")"
      - name: Release it to GitHub Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: gitpod-config-generator-0.0.1.vsix
